default:
  - Site: https://github.com
    Org: ansible-collections
    Repo: amazon.aws
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: ansible.netcommon
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: ansible.posix
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: ansible.windows
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: arista.eos
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: azure
    in_package: yes
  - Site: https://github.com
    Org: CheckPointSW
    Repo: CheckPointAnsibleMgmtCollection
    in_package: yes
  - Site: https://github.com
    Org: chocolatey
    Repo: chocolatey-ansible
    in_package: yes
  - Site: https://github.com
    Org: CiscoDevNet
    Repo: ansible-aci
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.asa
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: cisco.asa
    in_package: yes
  - Site: https://github.com
    Org: CiscoDevNet
    Repo: intersight-ansible
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: cisco.ios
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: cisco.iosxr
    in_package: yes
  - Site: https://github.com
    Org: CiscoDevNet
    Repo: ansible-meraki
    in_package: yes
  - Site: https://github.com
    Org: CiscoDevNet
    Repo: ansible-mso
    in_package: yes
  - Site: https://github.com
    Org: CiscoDevNet
    Repo: ansible-nso
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: nxos
    in_package: yes
  - Site: https://github.com
    Org: CiscoDevNet
    Repo: ansible-ucs
    in_package: yes
  - Site: https://github.com
    Org: cloudscale-ch
    Repo: ansible-collection-cloudscale
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.aws
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.azure
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.cassandra
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.crypto
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.digitalocean
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.docker
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.fortios
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.general
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.google
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: grafana
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.hashi_vault
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.hrobot
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.kubernetes
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: kubernetes.core
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.kubevirt
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.libvirt
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.molecule
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.mongodb
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.mysql
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.network
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.okd
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.postgresql
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.proxysql
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.rabbitmq
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.routeros
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: skydive
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.sops
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.vmware
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: vmware_rest
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.windows
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.yang
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.zabbix
    in_package: yes
  - Site: https://github.com
    Org: containers
    Repo: ansible-podman-collections
    in_package: yes
  - Site: https://github.com
    Org: cyberark
    Repo: ansible-conjur-collection
    in_package: yes
  - Site: https://github.com
    Org: cyberark
    Repo: ansible-security-automation-collection
    in_package: yes
  - Site: https://github.com
    Org: dell
    Repo: dellemc-openmanage-ansible-modules
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: dellemc.os10
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: dellemc.os6
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: dellemc.os9
    in_package: yes
  - Site: https://github.com
    Org: F5Networks
    Repo: f5-ansible
    in_package: yes
  - Site: https://github.com
    Org: fortinet-ansible-dev
    Repo: ansible-galaxy-fortimanager-collection
    in_package: yes
  - Site: https://github.com
    Org: fortinet-ansible-dev
    Repo: ansible-galaxy-fortios-collection
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: frr.frr
    in_package: yes
  - Site: https://github.com
    Org: gluster
    Repo: gluster-ansible-collection
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: google.cloud
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: hetzner.hcloud
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: ibm.qradar
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: ibm_zos_core
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: ibm_zos_ims
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: ibm.spectrum_virtualize
    in_package: yes
  - Site: https://github.com
    Org: infinidat
    Repo: ansible-infinidat-collection
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: junipernetworks.junos
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: mellanox.onyx
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp
    in_package: yes
  - Site: https://github.com
    Org: netapp-eseries
    Repo: santricity
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp
    in_package: yes
  - Site: https://github.com
    Org: netbox-community
    Repo: ansible_modules
    in_package: yes
  - Site: https://github.com
    Org: ngine-io
    Repo: ansible-collection-cloudstack
    in_package: yes
  - Site: https://github.com
    Org: ngine-io
    Repo: ansible-collection-exoscale
    in_package: yes
  - Site: https://github.com
    Org: ngine-io
    Repo: ansible-collection-vultr
    in_package: yes
  - Site: https://github.com
    Org: openstack
    Repo: ansible-collections-openstack
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: openvswitch.openvswitch
    in_package: yes
  - Site: https://github.com
    Org: ovirt
    Repo: ovirt-ansible-collection
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: pureport
    in_package: yes
  - Site: https://github.com
    Org: Pure-Storage-Ansible
    Repo: FlashArray-Collection
    in_package: yes
  - Site: https://github.com
    Org: Pure-Storage-Ansible
    Repo: FlashBlade-Collection
    in_package: yes
  - Site: https://github.com
    Org: sensu
    Repo: sensu-go-ansible
    in_package: yes
  # This is servicenow.servicenow which has been deprecated in favor of servicenow.itsm
  # https://github.com/ansible-community/community-topics/issues/44
  - Site: https://github.com
    Org: ServiceNowITOM
    Repo: servicenow-ansible
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: splunk.es
    in_package: yes
  - Site: https://github.com
    Org: theforeman
    Repo: foreman-ansible-modules
    in_package: yes
  - Site: https://github.com
    Org: T-Systems-MMS
    Repo: ansible-collection-icinga-director
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: vyos.vyos
    in_package: yes
  - Site: https://github.com
    Org: wtinetworkgear
    Repo: wti-collection
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: ansible.drill
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: ansible.network
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: ansible.security
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: ansible.utils
    in_package: yes
  - Site: https://github.com
    Org: CheckPointSW
    Repo: CheckPointAnsibleMgmtCollection
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: cisco.nxos
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: cloud.common
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: cloud.roles
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.ciscosmb
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.dns
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.elastic
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.grafana
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.healthchecksio
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.internal_test_tools
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.storage
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: Datadog
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: dellemc.enterprise_sonic
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: ibm_zos_cics
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: ibm_zos_sysauto
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: ibm.ds8000
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: logicmonitor
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp.aws
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp.azure
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp.cloudmanager
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp.elementsw
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp.ontap
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp.storagegrid
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp.um_info
    in_package: yes
  - Site: https://github.com
    Org: ansible-collections
    Repo: servicenow.itsm
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: symantec.epm
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: trendmicro.deepsec
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: vmware_rest_code_generator
    in_package: no
  - Site: https://github.com
    Org: ansible-collections
    Repo: vmware.vmware_rest
    in_package: no
