default:
  - Site: https://github.com
    Org: ansible-collections
    Repo: amazon.aws
  - Site: https://github.com
    Org: ansible-collections
    Repo: ansible.netcommon
  - Site: https://github.com
    Org: ansible-collections
    Repo: ansible.posix
  - Site: https://github.com
    Org: ansible-collections
    Repo: ansible.windows
  - Site: https://github.com
    Org: ansible-collections
    Repo: arista.eos
  - Site: https://github.com
    Org: ansible-collections
    Repo: azure
  - Site: https://github.com
    Org: CheckPointSW
    Repo: CheckPointAnsibleMgmtCollection
  - Site: https://github.com
    Org: chocolatey
    Repo: chocolatey-ansible
  - Site: https://github.com
    Org: CiscoDevNet
    Repo: ansible-aci
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.asa
  - Site: https://github.com
    Org: ansible-collections
    Repo: cisco.asa
  - Site: https://github.com
    Org: CiscoDevNet
    Repo: intersight-ansible
  - Site: https://github.com
    Org: ansible-collections
    Repo: cisco.ios
  - Site: https://github.com
    Org: ansible-collections
    Repo: cisco.iosxr
  - Site: https://github.com
    Org: CiscoDevNet
    Repo: ansible-meraki
  - Site: https://github.com
    Org: CiscoDevNet
    Repo: ansible-mso
  - Site: https://github.com
    Org: CiscoDevNet
    Repo: ansible-nso
  - Site: https://github.com
    Org: ansible-collections
    Repo: nxos
  - Site: https://github.com
    Org: CiscoDevNet
    Repo: ansible-ucs
  - Site: https://github.com
    Org: cloudscale-ch
    Repo: ansible-collection-cloudscale
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.aws
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.azure
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.cassandra
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.crypto
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.digitalocean
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.docker
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.fortios
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.general
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.google
  - Site: https://github.com
    Org: ansible-collections
    Repo: grafana
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.hashi_vault
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.hrobot
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.kubernetes
  - Site: https://github.com
    Org: ansible-collections
    Repo: kubernetes.core
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.kubevirt
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.libvirt
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.molecule
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.mongodb
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.mysql
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.network
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.okd
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.postgresql
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.proxysql
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.rabbitmq
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.routeros
  - Site: https://github.com
    Org: ansible-collections
    Repo: skydive
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.sops
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.vmware
  - Site: https://github.com
    Org: ansible-collections
    Repo: vmware_rest
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.windows
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.yang
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.zabbix
  - Site: https://github.com
    Org: containers
    Repo: ansible-podman-collections
  - Site: https://github.com
    Org: cyberark
    Repo: ansible-conjur-collection
  - Site: https://github.com
    Org: cyberark
    Repo: ansible-security-automation-collection
  - Site: https://github.com
    Org: dell
    Repo: dellemc-openmanage-ansible-modules
  - Site: https://github.com
    Org: ansible-collections
    Repo: dellemc.os10
  - Site: https://github.com
    Org: ansible-collections
    Repo: dellemc.os6
  - Site: https://github.com
    Org: ansible-collections
    Repo: dellemc.os9
  - Site: https://github.com
    Org: F5Networks
    Repo: f5-ansible
  - Site: https://github.com
    Org: fortinet-ansible-dev
    Repo: ansible-galaxy-fortimanager-collection
  - Site: https://github.com
    Org: fortinet-ansible-dev
    Repo: ansible-galaxy-fortios-collection
  - Site: https://github.com
    Org: ansible-collections
    Repo: frr.frr
  - Site: https://github.com
    Org: gluster
    Repo: gluster-ansible-collection
  - Site: https://github.com
    Org: ansible-collections
    Repo: google.cloud
  - Site: https://github.com
    Org: ansible-collections
    Repo: hetzner.hcloud
  - Site: https://github.com
    Org: ansible-collections
    Repo: community.qradar
  - Site: https://github.com
    Org: ansible-collections
    Repo: ibm.qradar
  - Site: https://github.com
    Org: ansible-collections
    Repo: ibm_zos_core
  - Site: https://github.com
    Org: ansible-collections
    Repo: ibm_zos_ims
  - Site: https://github.com
    Org: ansible-collections
    Repo: ibm.spectrum_virtualize
  - Site: https://github.com
    Org: infinidat
    Repo: ansible-infinidat-collection
  - Site: https://github.com
    Org: ansible-collections
    Repo: junipernetworks.junos
  - Site: https://github.com
    Org: ansible-collections
    Repo: mellanox.onyx
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp
  - Site: https://github.com
    Org: netapp-eseries
    Repo: santricity
  - Site: https://github.com
    Org: ansible-collections
    Repo: netapp
  - Site: https://github.com
    Org: netbox-community
    Repo: ansible_modules
  - Site: https://github.com
    Org: ngine-io
    Repo: ansible-collection-cloudstack
  - Site: https://github.com
    Org: ngine-io
    Repo: ansible-collection-exoscale
  - Site: https://github.com
    Org: ngine-io
    Repo: ansible-collection-vultr
  - Site: https://github.com
    Org: openstack
    Repo: ansible-collections-openstack
  - Site: https://github.com
    Org: ansible-collections
    Repo: openvswitch.openvswitch
  - Site: https://github.com
    Org: ovirt
    Repo: ovirt-ansible-collection
  - Site: https://github.com
    Org: ansible-collections
    Repo: pureport
  - Site: https://github.com
    Org: Pure-Storage-Ansible
    Repo: FlashArray-Collection
  - Site: https://github.com
    Org: Pure-Storage-Ansible
    Repo: FlashBlade-Collection
  - Site: https://github.com
    Org: sensu
    Repo: sensu-go-ansible
  - Site: https://github.com
    Org: ServiceNowITOM
    Repo: servicenow-ansible
  - Site: https://github.com
    Org: ansible-collections
    Repo: splunk.es
  - Site: https://github.com
    Org: theforeman
    Repo: foreman-ansible-modules
  - Site: https://github.com
    Org: T-Systems-MMS
    Repo: ansible-collection-icinga-director
  - Site: https://github.com
    Org: ansible-collections
    Repo: vyos.vyos
  - Site: https://github.com
    Org: wtinetworkgear
    Repo: wti-collection

