# Meetup config. These strings come from the Meetup URLs, eg
# https://www.meetup.com/Ansible-Atlanta
default:
  # Meetups we want to track
  allowlist:
    - Ansible-Ahmedabad
    - Ansible-Athens
    - Ansible-Atlanta
    - Ansible-Aurangabad
    - Ansible-Baltimore
    - Ansible-Bangalore
    - Ansible-Bangkok
    - Ansible-Barcelona
    - Ansible-Beijing
    - Ansible-Beirut
    - Ansible-Belgaum
    - Ansible-Benelux
    - Ansible-Berlin
    - Ansible-Bern
    - Ansible-Bogota
    - Ansible-Bordeaux
    - Ansible-Boston
    - Ansible-Boulder
    - Ansible-Brasilia
    - Ansible-Brisbane
    - Ansible-Brno
    - Ansible-Buenos-Aires
    - Ansible-Bulgaria
    - Ansible-Canberra
    - Ansible-Catania
    - Ansible-Charlotte
    - Ansible-Chennai
    - Ansible-Chicago
    - Ansible-Cincinnati
    - Ansible-Copenhagen
    - Ansible-Cork-Ireland
    - Ansible-Crete
    - Ansible-Dallas
    - Ansible-DC
    - Ansible-Delhi
    - Ansible-Denver
    - Ansible-Detroit
    - Ansible-Dhahran
    - Ansible-Dublin
    - Ansible-Durham
    - Ansible-Edinburgh
    - Ansible-Fort-Worth
    - Ansible-Frankfurt
    - Ansible-Geneva
    - Ansible-Guadalajara
    - Ansible-Hamburg
    - Ansible-Hangzhou
    - Ansible-Ha-Noi
    - Ansible-Hawaii
    - Ansible-Helsinki
    - Ansible-Hong-Kong
    - Ansible-Houston
    - Ansible-Hyderabad
    - Ansible-in-DevOps-Torun-Bydgoszcz
    - Ansible-Indianapolis
    - ansible-iraq
    - Ansible-Israel
    - Ansible-Jakarta
    - Ansible-Jalandhar
    - Ansible-Johannesburg
    - Ansible-Kansas-City
    - Ansible-Karlsruhe
    - Ansible-Kolkata
    - Ansible-Krakow
    - Ansible-Las-Vegas
    - Ansible-Leeds
    - Ansible-Lisbon
    - Ansible-London
    - Ansible-Los-Angeles
    - Ansible-Lyon
    - Ansible-Madrid
    - Ansible-Manchester
    - Ansible-Marseille
    - Ansible-Meetup-Dresden
    - Ansible-Mexico-City
    - Ansible-Miami
    - Ansible-Milan
    - Ansible-Minneapolis
    - Ansible-Montreal
    - Ansible-Moscow
    - Ansible-Mumbai
    - Ansible-Munchen
    - Ansible-Nairobi
    - Ansible-New-Zealand
    - Ansible-NOVA
    - Ansible-NYC
    - Ansible-Omaha
    - Ansible-Oxford
    - Ansible-Paris
    - Ansible-Perth
    - Ansible-Peru
    - Ansible-Philadelphia
    - Ansible-Phoenix
    - Ansible-Pisa
    - Ansible-Pittsburgh
    - Ansible-Portland
    - Ansible-Prague
    - Ansible-Pune
    - Ansible-Quebec
    - Ansible-Reggio-Emilia
    - Ansible-Rennes
    - Ansible-Republica-Dominicana
    - Ansible-Richmond
    - Ansible-Riga
    - Ansible-Rio-de-Janeiro
    - Ansible-Roma
    - Ansible-Salt-Lake-City
    - Ansible-San-Diego
    - Ansible-Sao-Paulo
    - Ansible-Seoul
    - AnsibleSF
    - Ansible-Shanghai
    - Ansible-Singapore
    - Ansible-SpaceCoast
    - Ansible-SPb
    - Ansible-St-Louis
    - Ansible-Stockholm
    - Ansible-Stuttgart
    - Ansible-Sydney
    - Ansible-Szczecin
    - Ansible-Taipei
    - Ansible-Tampa
    - Ansible-Toronto
    - ansible-vancouver-bc
    - Ansible-Warsaw
    - Ansible-Zurich
    - Awesome-Austin-Ansible-Assembly
    - Bay-Area-Ansible-User-Group
    - DevOps-Barranquilla
    - Hannover-Ansible-Meetup-Group
    - Melbourne-Ansible-User-Group
    - NEO-Ansible
    - Seattle-Ansible-Meetup
    - Vienna-Ansible-Meetup
  # Meetups we are sure we don't want to track
  ignorelist:
    - currently-this-is-an-empty-list

